//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.05 at 12:19:34 AM CST 
//


package com.hotels;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AmenityDetails" type="{http://hotels.com/soap}AmenityDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "amenityDetails"
})
@XmlRootElement(name = "EditAmenityDetailsResponse")
public class EditAmenityDetailsResponse {

    @XmlElement(name = "AmenityDetails", required = true)
    protected AmenityDetails amenityDetails;

    /**
     * Gets the value of the amenityDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AmenityDetails }
     *     
     */
    public AmenityDetails getAmenityDetails() {
        return amenityDetails;
    }

    /**
     * Sets the value of the amenityDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmenityDetails }
     *     
     */
    public void setAmenityDetails(AmenityDetails value) {
        this.amenityDetails = value;
    }

}
